language: node_js
node_js: 
  - "8"
  - "10"
  - "12"

script: npm run unit-test

defaults:
  build-stage: &buildstage
    stage: build
    script: npm run build
  integration-script: &integration-script
    script:
      - npm run build
      - node build_release_package_json.js
      - npm run integration-test
  test-integration: &test-integration
    stage: integration(test)
    <<: *integration-script
    if: branch =~ /^feature/
    env:
      - secure: "XJ6KFdEoEqcajZjMhJBT5UxFA6i/W0U0eUi61eeEv4MdF2fKg6kOgLmiPMoEJ+PQsAj2hT6FUJdFNS2HmTXWA5olSXlAMn9g7WLIjehRnKrdnpaYLWj+SQNN5a+DtFg5w1jfnR+jhuNK7zq1jUy0a1d6MRxrFJkfv222aapSvIfvp84UGQA12edz08JUP1c+8x5NA5rs+4qKTYwoCsMQwZ4wCpOXD7+CG6d87OOufLrYNSJ2LxIvj/rgPdlLZaMkwaWvTy6c+kkrDuL5nQ48mLZae0zmUiBR8EjIfKxN7+8Bn2EsTcWYx4re46hka+qc+wEcGYSA/SwPuToSkXUfPg06/qYgCmUm+kVoFe5ywiPGPA3rvU42Em2EJuW18sFaZKzbZI8fRfoPwZhFdFd3K7mzrYzXLUyNqTwvrX1jskQcbUn6ZRGHKXPnAXur9YtvIZ7XrIZo6CnAvQdm86HkGfYWKtt+CY9c5jRORKuDctr/BE3vgMa3hrGQXrDEe1l+iewhARX0rDZmSvcbZ/dYd81f4XudgIpA4FzE8OkduUDE9gngH96PcglrozoHMMTidflVRCAlh7Z5FprTuYkDMnMxn85U457x8YsXUf4A3nhtZQGqu6B5fsqIk4Z1k5jYjOBzHvar1ubhcVa8Cu7eBneOM36ChhSTmLCJKBB7FmI="
      - secure: "rMIaZbjPW6vevo5f550j+N3fN313oOo94SCL15zzwqiNWjctIPCXW7wr1XST/oEU/+YM+UvhGZ12aXQf/Bh+ptxbvqQ7N6II64qbYRGqKBQqt6lbaUYQvoKJHbxXV8wBMxXkfzrpwgHiVZ3Yp6SCsa7OaHTasa+H19svsIdyA6WgHWDGpAxe0gFnMlAX0bHk/T8Kbke3gP9k+V0rEzIrqihgHZtldJfd4dcAZGB/XC6+AyNrYHKdMjFTft3YZODcb5xXvBsaUhFCDylqNA997GtKHQbzcF5imFGxTHRzBXDceAKL6cs3pF604K5oy3WgDiU5JJMihO0jbSLbpv2VLj+CDAPSL97pKJmOFn0R/HKOn1uxjO5r31q+73EZwZu9uE6dCgj06tv5NLQ9TrcP3G0EA2l7yaCnm/tPwnYXdLab0qtCShnAFJIjaf0tQcqhM9BpAWNVuRIQjYsHOADn3GHUgRiWWg1MYl6EN8ORemenkvWTzIq6/5LZ+ycrjFqb1+paRBRauud97kMoR6AwHJnjayviCgEvY+51sDDZl9NBR6bH4WcJfQcWbvj9JWWBOnjrjGdeOsj2wTCY1IDAAtL/jXDJ73vN9hhJtZ35xegBY66D7g53ApTkdFLhWdQ7E0ngkoCHbTmU8Z5WeGSInnsdTOz7GbjmgOWqG6T5vOM="
  stage-integration: &stage-integration
    stage: integration(stage)
    <<: *integration-script
    if: (branch = develop) AND (NOT (tag IS present))
    env:
      - secure: "FaUl7XRw4IcbN8Sxt1fo3lgG8Adspsi5d3n1FKGGkHwPm36CVDf3WF9QpkOyy6eEyRLwo1AgeysfkpVmC7wcELK13mhloXsPf+bI7HOW7df9PFxQwKUzsnZSaxQ6JVgMybmOnt+8mkk/OS7cOGv0v2dhYwowOY/A0/NNGjl26frkRHdbN4fr3J3E8znNVLGXBWr7CaOQF2k5ptLEPF5xG9e/6/RHtg2UjQ8VYE6SkY/THkVFHbiqnlMJ+L8mjLlunlG25OCsriAtaOgrGq0EwP8c8cmWMevuO5TqwHp/v8/c/ny9Rm9XKxfho8RX8meivBBB5GtFwxiboGZeA6XeZFQYKr647f888EThzJA36lQONH9FJVkBWf19m00nbakWzt/XSdk8Rl6ytwsAFeF9ACYr8uKs/n8bGNGKrksE22Tf4Kp3TZYGtfAGivc8AHtLUeXdeTSiT347U1HGmiXrS4ehbX1ZVc6Rv6eqAOMkGYunNttyDkohc5b8L6IRv4U2DcIXXQFV1ZjDrDp9+xQlHT9McD7tjLVugGL5lkCaVomkJXAiBE5UWIou69OrhSqcbZ1RH/ZLJG5XLt2H5Pf4SwwTFC3wHlnSdFB0xVYNiUciKVK0bAOFNDRHN81H4dlVTI2TetMEGsP7u/WnpkZp/JU+PjiXoeHhZXAUzr9ZEAo="
      - secure: "C2q4/QklhoekOD4hhx2aM0nSXvPvHxHMFQkArK2gOse1GcRfpL8xv+t8XlhAkE3iaRQwF4Rcy6AzNrsSWbBzp2RuBhxkoZH+Wxp21XRDIKbHUruDBer5Coi/Ik1zPu2WL7/VaDXnntsiFcG8qV+slg8Ey4KkuouKxuEVanscWdj8UwwtZ5a/OhvYFs+h3/VkVTThCSrqM8aGkQBrWlWq5fsIEqsf1sulc5IXosx5XGxzB6mMRWVzGYXAYgOZnj1+kcH4wYormCTzV7+JulFHCnDEUzJCXpKnObwWofzGabp41Mu+76w5NueA8ptROmGUS4JBbYUyfZU55IXunQT7FcyG7nqQvl5RHL8SKIadkWL0y/lZypVDUB29acAKZkOA0YDWOFQU4AgXuNbpVrdhMyAom3KgIpJ3uYlVFe1Mxy8MOzfVLu4VjN0RCyxcCoRBWjNduRby6cLenVFRG71Mba/9tZoXVwS8plMj4NYzlpz2BgT0jDJyqh6ybu0NwQz+7X091BKTyI3cBwazMwEMIXkWBAe5XJrnSw5d4xkY5A1asst5Hq5tAACA5u9XMqsY6sWngBv7rOU+JIWN9rnD2Twi3OskWJ0iDCmQmmFYhsufEUWFxO5I7xXSExnPwViHaTsblxtouKRVKmaiPVU0kZCgOmuFYb7aew+ADsK/K3I="    
  prod-integration: &prod-integration
    stage: integration(prod)
    <<: *integration-script
    if: tag =~ /[0-9]+\.[0-9]+\.[0-9]/
    env:
      - secure: "CUzIljZgD7fo2/3kWMtUz4DXFfwyXlXzak5s1bpYYw6u2a6F5EaLRDDim78wpOJiRu3OeFfVyD+YxE5/4GXXQQ7kFGTyXxihadp34XCwNd5Wbivzc5OFBaD45zYoaM/taMUALN45sDsto3GtkPA1kp1QXyd7EQczYAzpGWRpwoi1TLVsXWV/Zruat14aYdVXZ1D386meImGnXoaEAlU0rEsGs+Uu8o+TsNce+MnAXNw8wIem2bb4WWLQeOBRhQUT0KekhYKVQyWn4eymXUsJ7VdxMmJ0hDanhB9kxtKj75YG2yLjDBGfe5iPCIuctY9Aq3Kbsm6SI1WqthfrfjObc37DXGp9Bz7ORQVJbUoyXodHgchm14KPTSfKsuMGfRf0MBoPcMDxedHkBy0SiIRfFmDYDZTDKbBPbpge2lXMA75GqritqhAgMyyGYq5IL2Q3p1bKL2i7mjIz/K96MWTqe9NZszYLRm0P5MnNVsHYiuJX3KcBQ3ZUi9mTupTs45dQh8H9U0cj4g7Dq+/OHWRyKhV68J9m4gMZP21zdu8Dcd0FozGHQ2swRHiPVE0IZ1kggPzazfUmr3SKAulM5OSTnkXWbTPwhyRlcghcMt2tGguQmGXrOzw22SXRuRk3ui1TXB36p/kXCs5AR35b1KGB8f/LxYu9ca5JZ9M8Y6Hrt6A="
      - secure: "dEBXkYomLNZKj9i4U498p0twztB2Re8vJCOTc2jP2ESGANbr1QP3+KZRR3y4xz4FKHfGe84wLVsfh7zHmkdPmk0g5EcdqrXRY0Cy/bY+j2mX8C4PRNxC5GqDQ5zGKDaHPhGOQtaDTzaGlE+K8RZeC0txmDxkQl15/gUYaJD+PhtSCXFtNOacmdi/sUbiazG1TdvRqiEqka2kYFfCXJOLWIsnu5YdvX0kT3CW/yFc2OK2+W3cibachEExApJ8vbmCwz/4vT+M0huYblo7z5YbMWUU8c6N9V7AeGv+7Ult5fsds6fITjUrlHkjbLgB5qkkXhydJUm1FbPi85qlPY2c8pfR1kGomATmQt/d1lpr2+fqMDa1mrvRMpYPoyy7o7oWGimxJurL8pFwrfnI7xHsKxIYXV4AQwfPvnL7b3jyrd0B494TVonyLFgMmXC0WsKWT3t0paq1sOhj9uuxAB064kAqNceYFRYQCI18ILZL5+jAg3aWNv2mloTR1dVoA+z5RQhYUE8Ip/QRHvAazihK9ugOLbkhHTixFV7IJlrm+/1qDt46Bkm9T7/qnhgzaz7RfX7PCU7JwBpputCXY4ZqTu3tiDuPZYqHQuBG8hTPpCIxgQJdK55bon1SGw+8EC8ZW9ZxHSnU8DRwitdgMXBT94Vs/UDR63JC1zEZgu2ElGY="

jobs:
  include:
    - stage: lint
      script: npm run lint
    - <<: *buildstage
      node_js: "8"
    - <<: *buildstage
      node_js: "10"
    - <<: *buildstage
      node_js: "12"
    - <<: *test-integration
      node_js: "8"
    - <<: *test-integration
      node_js: "10"
    - <<: *test-integration
      node_js: "12"
    - <<: *stage-integration
      node_js: "8"
    - <<: *stage-integration
      node_js: "10"
    - <<: *stage-integration
      node_js: "12"
    - <<: *prod-integration
      node_js: "8"
    - <<: *prod-integration
      node_js: "10"
    - <<: *prod-integration
      node_js: "12" 

notifications:
  slack:
    secure: aZgSQDJHiWcdE6OAuDRruTZMIHp4lzvU+1SkQcxMdQ/5UDtFaFCUOTQXLqgGhEAkmwFX00Z16u0Nf4zu8RVC8do/5yeEg3Gs11q/E8R9BEDMGqANGEpqcUTmEHdu29DKoSW7MWrNR1wpigzNYV2Tb0jcXHefIIGtezmczP5aje4Bxv9mJq2+xtIYIr0+WnByg9vFcLvh+zIatlB2se3KboQKFeZ7M8Ptvx8bzD9Qsy0W0HOdLGdccUYxM+AuK1OM0acBObNQ/I9iorjFeJ1Y2UGCXaxhhKkHtbnEbnK38lVIkQRSl8plMIn7kVT1+r/buzcFSPDflXPwYWBHsWdEaMMQet+psbTd5I0iYzoo3eE9ed1610xDyKbVnNeRiPJ+UT1bsHI4UdhhsdwfVHcn9RG2dEuChEWFmvRucl1KxUQoaTXwIiondykXzj0VqJoEtpRvoaCjtwhzhUP6ovwQiX8nRv0V8d78jTn9QNcVC1yWashQRHCTf8eeu955IQYUUk1/iyt4e/J1h9siDwA7qkOuWudvPwkvmYpkXrjeyh2xT0pcGpR6a6mIy8uqN81qU0xmiYtByj8chivsNSQi+w4IixrAD/lCipfqPwUsBp3Mec62P4sXW0LU8iQRbtUSa900+Ch450lJOMnyKL5zxmW7UIb2mpH8uOp+sPf/qVM=
    if: (tag =~ /[0-9]+\.[0-9]+\.[0-9]/) OR (branch = develop)
    template: "%{repository_name} build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) by %{author} %{result} after %{duration}"
    on_success: always
    on_failure: always